name: buscaprodmt
description: Buscaprodmt
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.1.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
    
  http: ^1.1.0
  share_plus: ^7.2.2
  path_provider: ^2.1.2
  shared_preferences: ^2.2.2
  move_to_background: ^1.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
  assets:
  - assets/not_found.png
  - assets/buscador.png
